### ISSUE TITLE
Unification too offensive

### ISSUE THREAD

**Issue by jburse** [sasagawa888/nprolog#27]
Hi Ken,

It could be that you apply some substitution too early. But the
below hangs:

![image](https://user-images.githubusercontent.com/5411487/53916312-29934200-4062-11e9-9644-a084ec03b646.png)

**Comment by jburse** [comment]
On the other hand a trivial Prolog can handle it:

![image](https://user-images.githubusercontent.com/5411487/53916327-3a43b800-4062-11e9-8879-fefbc1780c12.png)

**Comment by jburse** [comment]
I got the test case from Tau Prolog:

https://github.com/jariazavalverde/tau-prolog/issues/5#issuecomment-470287300

**Comment by sasagawa888** [comment]
Usualy, Prolog does not check occurs-check.
