### ISSUE TITLE
doubts about random

### ISSUE THREAD

**Issue by jburse** [sasagawa888/nprolog#34]
Hi,

Was testing the O-Prolog random/1 evaluable function. SWI-Prolog 
X is random(N), generates a number in the range 0..N-1.

I don't understand what range O-Prolog will generate, it seems
the range is 0..N. At least I get:

![image](https://user-images.githubusercontent.com/5411487/57402975-d7dd7400-71d8-11e9-897d-0bce3d8af244.png)

**Comment by jburse** [comment]
On the other hand, if I try the same for SWI-Prolog I get. Basically
I can wait, and it never results in 21:

![image](https://user-images.githubusercontent.com/5411487/57403020-f3487f00-71d8-11e9-8fa2-f19f13ebfddb.png)

**Comment by sasagawa888** [comment]
N-Prolog Ver 0.03
?- repeat,X is random(20).
X = 4;
X = 4;
X = 0;
X = 16;
X = 16;
X = 20;
X = 0;
X = 4;
X = 0
yes
?-
