### ISSUE TITLE
if-then-else not reentrant

### ISSUE THREAD

**Issue by jburse** [sasagawa888/nprolog#36]
Hi Ken,

Was testing some if-then-else again. A typical pattern of if-then-else,
is to use for once/1, like here:

```
p(a).
p(b).
?- p(X) -> true; fail.
X=a;
no
```
Now its of course also possible to call if-then-else multiple times, and
the expected result is as follows:
```
?- p(Y), (p(X) -> true; fail).
Y = a,
X = a ;
Y = b,
X = a ;
no
```

Somehow this seems not to work correctly:

![image](https://user-images.githubusercontent.com/5411487/59564114-1faab300-9043-11e9-87b4-14cc887b7fb7.png)

**Comment by jburse** [comment]
The solution Y=b,X=b should be produced.

You can compare to SWI-Prolog:

![image](https://user-images.githubusercontent.com/5411487/59564118-3c46eb00-9043-11e9-88a7-a7de4a868dad.png)

Or with GNU Prolog:

![image](https://user-images.githubusercontent.com/5411487/59564127-6698a880-9043-11e9-925e-5378a21c8cb1.png)

**Comment by jburse** [comment]
Might be related to:
https://github.com/sasagawa888/opl/issues/6

But its not really the same issue, the issue here doesn't use some cut.

**Comment by sasagawa888** [comment]
Fixed.
N-Prolog Ver 0.03
?- assert(p(a)).
yes
?- assert(p(b)).
yes
?- p(Y), (p(X) -> true; fail).
Y = a
X = a;
Y = b
X = a;
no
?-
