### ISSUE TITLE
listing does not show foward slashes

### ISSUE THREAD

**Issue by da-poodle** [sasagawa888/nprolog#50]
It appears that characters like \n are working but don't show when listing the predicate. 

This is a bit confusing but functionally ok, so minor. 

The following session should show the issue: 

```
    N-Prolog Ver 1.0
    ?- assert(test('\n')).
    yes
    ?- listing.
    test('n').
    yes
    ?- test('\n').
    yes
    ?- test('n').
    no
    ?-
```

**Comment by sasagawa888** [comment]
Fixed it.
Thank you.

N-Prolog Ver 1.0
?- assert(test('\n')).
yes
?- listing.
test('\n').
yes
?- test('\n').
yes
?- test('n').
no
?-
