### ISSUE TITLE
Trying to override the ',' or ';' operators causes the parser to crash

### ISSUE THREAD

**Issue by da-poodle** [sasagawa888/nprolog#51]
When trying to override the conjunction or disjunction operators the npl crashes. This occurs when using assert or if the predicate is in a file. 

If it is not valid to override the conjunction or disjunction operators then an error is expected. 

For example the unify operator will throw an error: 
```
?- assert((=(A,B,C) :- ifthenelse(A = B, C = true, C = false))).
Permission error assertz A=B
```
However with conjuction: 
```
?- assertz((','(A,B,C) :- A , B, C = true)).
Segmentation fault (core dumped)
```
And disjunction:
```
?- assertz((';'(A,B,C) :- (A ; B), C = true)).
Segmentation fault (core dumped)
```

**Comment by sasagawa888** [comment]
Fixed it.
Thank you.

N-Prolog Ver 1.0
?- assertz((','(A,B,C) :- A , B, C = true)).
Permission error assertz  A,B:-call(A),call(B),C=true
?- assertz((';'(A,B,C) :- (A ; B), C = true)).
Permission error assertz  A;B:-(call(A);call(B)),C=true
?-
