### ISSUE TITLE
if-then-else not cut transparent in then part

### ISSUE THREAD

**Issue by jburse** [sasagawa888/nprolog#6]
I get the following result:

O-Prolog Ver 1.70 (Chisato)
| ?- (X=1;X=2), (true->!; fail), (Y=1;Y=2).
X = 1
Y = 1;
X = 1
Y = 2;
X = 2
Y = 1;
X = 2
Y = 2;
no

**Comment by jburse** [comment]
But according to the ISO core standard the if-then-else should be
cut transparent in both the then part and the else part. So the
expected result is as in GNU Prolog:

```
GNU Prolog 1.4.5 (64 bits)

| ?- (X=1;X=2), (true->!; fail), (Y=1;Y=2).

X = 1
Y = 1 ? ;

X = 1
Y = 2
```

**Comment by sasagawa888** [comment]
Fixed.
N-Prolog Ver 0.03
?- (X=1;X=2), (true->!; fail), (Y=1;Y=2).
X = 1
Y = 1;
X = 1
Y = 2;
no
?-
