### ISSUE TITLE
Will not compile on Mac OS Catalina

### ISSUE THREAD

**Issue by JTurco32** [sasagawa888/nprolog#62]
Hello,

I thought id let people know that this will not compile on Mac OS Catalina even with xcode command line tools installed. I know you didn't test it on there, but this is for anyone who comes here and want's to try it on their mac.

**Comment by sasagawa888** [comment]
I would appreciate it if anyone could improve it so that it works on MacOS.

**Comment by sasagawa888** [comment]
What if you change GCC to CC in your makefile?
