### ISSUE TITLE
 disjunction disappears inside call/1

### ISSUE THREAD

**Issue by jburse** [sasagawa888/nprolog#7]
Disjunction usually works okay in O-Prolog:

```
O-Prolog Ver 1.70 (Chisato)
| ?- (Y=foo;Y=bar), write(Y), nl.
foo
Y = foo;
bar
Y = bar;
no
```

But when used inside call/1, I get the following result:

```
| ?-X=((Y=foo;Y=bar), write(Y), nl), call(X).
foo
X = (foo=foo;foo=bar,write(foo),nl)
Y = foo;
no

```

**Comment by jburse** [comment]
You can check GNU Prolog what the expected result
according to the ISO core standard is:

```
GNU Prolog 1.4.5 (64 bits)

| ?- X=((Y=foo;Y=bar), write(Y), nl), call(X).
foo

X = ((foo=foo;foo=bar),write(foo),nl)
Y = foo ? ;
bar

X = ((bar=foo;bar=bar),write(bar),nl)
Y = bar

(16 ms) yes
```

**Comment by sasagawa888** [comment]
Fixed.
N-Prolog Ver 0.03
?- X=((Y=foo;Y=bar), write(Y), nl), call(X).
foo
X = (foo=foo;(foo=bar),write(foo),nl)
Y = foo;
bar
X = (bar=foo;(bar=bar),write(bar),nl)
Y = bar;
no
?-
