### ISSUE TITLE
Local/Remote Crash (DoS) in SET_CAR

### ISSUE THREAD

**Issue by Halcy0nic** [sasagawa888/nprolog#74]
Hi!

Love the npl tool, I think it's super creative and really easy to use.

## Brief Summary
While I was using the tool I had my fuzzer running in the background and came across a local/remote crash (DoS condition) as a result of slightly malformed input.  Running the tool as a daemon/service (via inetd or some other means) would cause it to crash for all users accessing npl.  The issue comes from invoking the SET_CAR function on an Atom when the input is malformed.

## Reproduction
I've attached the input for reproduction purposes.  After running npl against the input you can see following the GDB trace:

```
./npl -s ./input_file
 ```
![gdb_nprolog_segfault](https://user-images.githubusercontent.com/42481692/177613786-91246a1e-e7e1-4245-b28f-3839a8b77be2.png)

![gdb_nprolog_set_car](https://user-images.githubusercontent.com/42481692/177613799-6bb1d8a5-af1d-4103-b747-6bcda1bfa97e.png)

Below is the hex dump of the input file:
![xxd_crash_nprolog](https://user-images.githubusercontent.com/42481692/177614795-f9b9b7b2-3dda-4c81-9c6e-c0d3dd04d383.png)

A similar process could be repeated for GET_CAR
[files.zip](https://github.com/sasagawa888/nprolog/files/9057188/files.zip)

**Comment by sasagawa888** [comment]
Thank you for the bug report. I will consider how to deal with it.

**Comment by sasagawa888** [comment]
I fixed it. I changed to consult/1 from reconsult/1  in -s mode.

tests/bug.pl
.0.

npl -s tests/bug.pl
Syntax error assertz  .0
around here line=1 column=0
?-

**Comment by Halcy0nic** [comment]
Sweet!

Thanks
