### ISSUE TITLE
list([]) resolves to no

### ISSUE THREAD

**Issue by da-poodle** [sasagawa888/nprolog#84]
Ignore me if this is actually correct behaviour, but if I call `list/1` with an empty list then I get 'no', If I call with a list with elements then I get 'yes'.

**Comment by da-poodle** [comment]
For example: 
```
  ?- list([]).
  no
  ?- list([a]).
  yes
```

**Comment by sasagawa888** [comment]
That's a bug. It will be fixed in the next version. Thank you.

**Comment by sasagawa888** [comment]
Fixed.
